language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
install: 
  - sudo pip install -r requirements.txt
  - sudo pip install coveralls
  - sudo pip install coverage
script: sudo coverage run --source . test.py
after_success:
  sudo coveralls